baseURL = 'https://surfbuddy.net/'
languageCode = 'en-us'
title = 'SurfBuddy - 0.37.0'
theme = "surfbuddy-theme"
[menu]
  [[menu.main]]
    url = "/"
    name = "Home"
    identifier = "home"
    pre = "home"
    weight = 1
  [[menu.main]]
    URL = "/usage/"
    name = "Usage"
    identifier = "usage"
    pre = "file"
    weight = 2
[outputs]
  home = ["HTML", "RSS", "JSON"]